# Generated by Django 6.0.4 on 2026-04-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(max_length=50, unique=True)),
                ('icone', models.CharField(blank=True, max_length=100, null=True)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id_commune', models.AutoField(primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(max_length=50, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'db_table': 'commune',
            },
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id_metier', models.AutoField(primary_key=True, serialize=False)),
                ('nom_metier', models.CharField(max_length=80)),
                ('est_actif', models.BooleanField(default=True)),
                ('id_categorie', models.ForeignKey(db_column='id_categorie', on_delete=django.db.models.deletion.RESTRICT, related_name='metiers', to='services.categorie')),
            ],
            options={
                'verbose_name': 'Métier',
                'verbose_name_plural': 'Métiers',
                'db_table': 'metier',
            },
        ),
    ]
