# Generated by Django 6.0.4 on 2026-05-07 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0002_remove_prestataire_id_categorie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom_categorie'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ['nom_commune'], 'verbose_name': 'Commune', 'verbose_name_plural': 'Communes'},
        ),
        migrations.AlterModelOptions(
            name='metier',
            options={'ordering': ['nom_metier'], 'verbose_name': 'Métier', 'verbose_name_plural': 'Métiers'},
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duree_estimee', models.IntegerField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_categorie', models.ForeignKey(db_column='id_categorie', on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='services.categorie')),
                ('id_metier', models.ForeignKey(db_column='id_metier', on_delete=django.db.models.deletion.RESTRICT, related_name='services', to='services.metier')),
                ('id_prestataire', models.ForeignKey(db_column='id_prestataire', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.prestataire')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
                'ordering': ['-date_creation'],
            },
        ),
    ]
