# Generated by Django 6.0.4 on 2026-05-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_categorie_options_alter_commune_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duree_estimee',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tarif',
        ),
        migrations.AddField(
            model_name='service',
            name='duree_max',
            field=models.IntegerField(blank=True, help_text='Durée maximum en minutes', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='duree_min',
            field=models.IntegerField(blank=True, help_text='Durée minimum en minutes', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tarif_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix maximum en FCFA', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tarif_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix minimum en FCFA', max_digits=10, null=True),
        ),
    ]
