# Generated by Django 6.0.4 on 2026-04-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id_avis', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('est_modere', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'db_table': 'avis',
                'ordering': ['-date_avis'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'message',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('type_demande', models.CharField(choices=[('directe', 'Réservation directe'), ('devis', 'Demande de devis')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('description_besoin', models.TextField(blank=True, null=True)),
                ('date_souhaitee', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'reservation',
                'ordering': ['-date_creation'],
            },
        ),
    ]
