# Generated by Django 6.0.4 on 2026-04-21 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id_destinataire',
            field=models.ForeignKey(db_column='id_destinataire', on_delete=django.db.models.deletion.RESTRICT, related_name='messages_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='id_expediteur',
            field=models.ForeignKey(db_column='id_expediteur', on_delete=django.db.models.deletion.RESTRICT, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_client',
            field=models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='users.client'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_prestataire',
            field=models.ForeignKey(db_column='id_prestataire', on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='users.prestataire'),
        ),
        migrations.AddField(
            model_name='message',
            name='id_reservation',
            field=models.ForeignKey(db_column='id_reservation', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='avis',
            name='id_reservation',
            field=models.OneToOneField(db_column='id_reservation', on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='reservations.reservation'),
        ),
    ]
