# Generated by Django 6.0.4 on 2026-05-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
        ('services', '0002_alter_categorie_options_alter_commune_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id_service',
            field=models.ForeignKey(blank=True, db_column='id_service', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='services.service'),
        ),
    ]
