# Generated by Django 6.0.4 on 2026-05-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_message_photo_message_type_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code_validation',
            field=models.CharField(blank=True, help_text='Code donné au prestataire après paiement', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_liberation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(blank=True, help_text='orange / mtn / wave', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='montant_commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la commission ServiceLink', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='montant_prestataire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant net reçu par le prestataire', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('bloque', 'Payé — En attente de validation'), ('libere', 'Libéré au prestataire'), ('rembourse', 'Remboursé au client'), ('litige', 'En litige')], default='non_paye', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='taux_commission',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Commission ServiceLink en %', max_digits=5),
        ),
        migrations.AddField(
            model_name='reservation',
            name='telephone_paiement',
            field=models.CharField(blank=True, help_text='Numéro utilisé pour le paiement', max_length=20, null=True),
        ),
    ]
