# Generated by Django 6.0.4 on 2026-05-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_code_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code_validation',
            field=models.CharField(blank=True, help_text='Code donné au client après paiement', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paiement_requis', 'Paiement requis'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
