# Generated by Django 6.0.4 on 2026-04-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id_abonnement', models.AutoField(primary_key=True, serialize=False)),
                ('type_offre', models.CharField(choices=[('mensuel', 'Mensuel — 5 000 FCFA'), ('annuel', 'Annuel — 50 000 FCFA')], max_length=20)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'abonnement',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operateur', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('wave', 'Wave'), ('moov', 'Moov Money')], max_length=20)),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('reverse', 'Reversé'), ('bloque', 'Bloqué')], default='en_attente', max_length=50)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('date_reversement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiement',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
