# Generated by Django 6.0.4 on 2026-04-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('reservations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='id_prestataire',
            field=models.ForeignKey(db_column='id_prestataire', on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='users.prestataire'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='id_reservation',
            field=models.OneToOneField(db_column='id_reservation', on_delete=django.db.models.deletion.RESTRICT, related_name='paiement', to='reservations.reservation'),
        ),
    ]
