# Generated by Django 6.0.4 on 2026-04-21 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=50, unique=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('commune_residence', models.CharField(blank=True, max_length=50, null=True)),
                ('id_utilisateur', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id_prestataire', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_profil', models.CharField(blank=True, max_length=255, null=True)),
                ('est_premium', models.BooleanField(default=False)),
                ('est_verifie', models.BooleanField(default=False)),
                ('date_fin_premium', models.DateField(blank=True, null=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('badge_top', models.BooleanField(default=False)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_disponible', models.BooleanField(default=True)),
                ('id_categorie', models.ForeignKey(db_column='id_categorie', on_delete=django.db.models.deletion.RESTRICT, related_name='prestataires', to='services.categorie')),
                ('id_metier', models.ForeignKey(db_column='id_metier', on_delete=django.db.models.deletion.RESTRICT, related_name='prestataires', to='services.metier')),
                ('id_utilisateur', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='prestataire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestataire',
                'verbose_name_plural': 'Prestataires',
                'db_table': 'prestataire',
            },
        ),
    ]
