# Generated by Django 6.0.4 on 2026-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestataire',
            name='id_categorie',
        ),
        migrations.RemoveField(
            model_name='prestataire',
            name='id_metier',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(db_column='mot_de_passe', max_length=255),
        ),
    ]
