# Generated by Django 6.0.4 on 2026-05-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_prestataire_id_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='prestataires/photos/%Y/%m/'),
        ),
    ]
