# Generated by Django 6.0.4 on 2026-05-25 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_prestataire_photo_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id_favori', models.AutoField(primary_key=True, serialize=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='users.client')),
                ('id_prestataire', models.ForeignKey(db_column='id_prestataire', on_delete=django.db.models.deletion.CASCADE, related_name='mis_en_favori', to='users.prestataire')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'db_table': 'favori',
                'ordering': ['-date_ajout'],
                'unique_together': {('id_client', 'id_prestataire')},
            },
        ),
    ]
