# Generated by Django 6.0.4 on 2026-06-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_favori'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id_message_contact', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('sujet', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('est_traite', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'db_table': 'message_contact',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
